# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_analise.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_analise.proto\x12\nmensageiro\"\x17\n\x15Resposta_Request_Void\"(\n\x15Resposta_Request_Long\x12\x0f\n\x07message\x18\x01 \x01(\x02\"*\n\x17Resposta_Request_String\x12\x0f\n\x07message\x18\x01 \x01(\t2\x8f\x03\n\nMensageiro\x12]\n\x13\x45nviarMensagemVazia\x12!.mensageiro.Resposta_Request_Void\x1a!.mensageiro.Resposta_Request_Void\"\x00\x12\\\n\x12\x45nviarMensagemLong\x12!.mensageiro.Resposta_Request_Long\x1a!.mensageiro.Resposta_Request_Long\"\x00\x12`\n\x16\x45nviarMensagemOitoLong\x12!.mensageiro.Resposta_Request_Long\x1a!.mensageiro.Resposta_Request_Long\"\x00\x12\x62\n\x14\x45nviarMensagemString\x12#.mensageiro.Resposta_Request_String\x1a#.mensageiro.Resposta_Request_String\"\x00\x42+\n\x0fio.grpc.analiseB\x0fMensageiroProtoP\x01\xa2\x02\x04Mensb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_analise_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017io.grpc.analiseB\017MensageiroProtoP\001\242\002\004Mens'
  _RESPOSTA_REQUEST_VOID._serialized_start=34
  _RESPOSTA_REQUEST_VOID._serialized_end=57
  _RESPOSTA_REQUEST_LONG._serialized_start=59
  _RESPOSTA_REQUEST_LONG._serialized_end=99
  _RESPOSTA_REQUEST_STRING._serialized_start=101
  _RESPOSTA_REQUEST_STRING._serialized_end=143
  _MENSAGEIRO._serialized_start=146
  _MENSAGEIRO._serialized_end=545
# @@protoc_insertion_point(module_scope)
